version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files/:/home/:ro
    ports:
      - "80:80"
